version: "3.9"

services:
  db:
    image: postgres:16
    container_name: reliability_db
    restart: always
    environment:
      POSTGRES_USER: reliability
      POSTGRES_PASSWORD: reliability
      POSTGRES_DB: reliability
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
